name: Create artifact summary

description: "Creates a job summary with Nexus links to the produced artifacts"

inputs:
  build-version:
    type: string
    required: true
  solution:
    type: string
    required: true
  warn-if-empty:
    type: boolean
    required: false
    default: true  

runs:
  using: "composite"
  steps:
    - name: Create summary
      shell: pwsh
      run: |
        if ((Get-ChildItem -Path ".\publish\compressed-installers" -Force | Measure-Object).Count -gt 0)
        {
          Get-ChildItem -Path .\publish\compressed-installers | ForEach-Object {
              $Component = $_.Name.Replace("Installers.zip", "");
              $Filename = $_.Name
          }
          $Summary = "This is the summary"
          $Summary = $Summary + "`n" + "github.event_name=${{ github.event_name }}, build-version=${{ inputs.build-version }}, solution=${{ inputs.solution }}"
          echo "$Summary" >> $env:GITHUB_STEP_SUMMARY
        }
        else if ("${{ inputs.warn-if-empty }}" -eq "true")
        {
          
        }

        