name: Create artifact summary

description: "Creates a job summary with Nexus links to the produced artifacts"

inputs:
  build-version:
    type: string
    required: true
  solution:
    type: string
    required: true
  warn-if-empty:
    type: boolean
    required: false
    default: true  

runs:
  using: "composite"
  steps:
    - name: Create summary
      shell: pwsh
      run: |
        $Summary = "### Version ${{ inputs.build-version }}"
        $Summary = $Summary + "`nBranch: [Nexus link](https://google.com)"
        $Summary = $Summary + "`nRelease metadata: [Nexus link](https://google.com)"
        $Summary = $Summary + "`nChangelog: [Nexus link](https://google.com)"

        if ((Get-ChildItem -Path ".\publish\compressed-installers" -Force | Measure-Object).Count -gt 0)
        {
          $Summary = $Summary + "`n<details><summary>Installers</summary>"
          Get-ChildItem -Path .\publish\compressed-installers | ForEach-Object {
            $Component = $_.Name.Replace("Installers.zip", "");
            $Filename = $_.Name

            $Summary = $Summary + "`n`n**$Component**"
            $Summary = $Summary + "`n[Nexus link for $Filename](https://google.com)"
          }
          $Summary = $Summary + "`n</details>"
        }
        elseif ("${{ inputs.warn-if-empty }}" -eq "true")
        {
          
        }


        echo "$Summary" >> $env:GITHUB_STEP_SUMMARY

        