name: 'Test reporting'

on:
  push:
  pull_request:
  workflow_dispatch:
  
permissions:
  contents: read
  actions: read
  checks: write  
  
jobs:
  build-and-test:
    name: 'Build, test and report'
    runs-on: windows-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: 'Recursive lookup'
        uses: nih-milestone/trx-parser@main
        with:
          TRX_PATH: ${{ github.workspace }}\TestResults
        
      - name: 'Roll dice'
        shell: pwsh
        run: echo "PASS=$(Get-Random -Maximum 3)" >> $env:GITHUB_ENV
       
      - name: 'Parse - Failing results'
        if: env.PASS > 0
        uses: nih-milestone/trx-parser@main
        with:
          TRX_PATH: ${{ github.workspace }}\FailingTestResults
          TRX_GROUPING: 100
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          
      - name: 'Parse - Passing results'
        if: env.PASS == 0
        uses: nih-milestone/trx-parser@main
        with:
          TRX_PATH: ${{ github.workspace }}\PassingTestResults
          TRX_GROUPING: 100
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}