name: 'Test reporting'

on:
  push:
  workflow_dispatch:
  pull_request:
  
permissions:
  contents: read
  actions: read
  checks: write  
  
jobs:
  build-and-test:
    name: 'Build, test and report'
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: 'Parse - Failing results'
        if: false
        uses: nih-milestone/trx-parser@v0.5.7
        with:
          TRX_PATH: ${{ github.workspace }}\FailingTestResults
          TRX_GROUPING: 50
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          
      - name: 'Parse - Passing results'
        if: false
        uses: nih-milestone/trx-parser@v0.5.7
        with:
          TRX_PATH: ${{ github.workspace }}\PassingTestResults
          TRX_GROUPING: 50
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: app_token
        uses: tibdex/github-app-token@v2
        env:
          OPENSSL_CONF: /dev/null  # https://github.com/tibdex/github-app-token/issues/54
        with:
          app_id: 855383
          private_key: ${{ secrets.PRIVATE_KEY_CHECKS_API_APP }}

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV          

      - name: Create Check Run
        env:
          GH_TOKEN: ${{ steps.app_token.outputs.token }}
#          GH_TOKEN: ${{ github.token }}
        run: |
          gh api -X POST -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -f 'name=A Mighty Test' \
          -f 'head_sha=${{ github.sha }}' \
          -f 'status=completed' \
          -f 'conclusion=success' \
          -f 'output[title]=A Mighty Title' \
          -f 'output[summary]=A Mighty Summary - ${{ github.run_id }} - ${{ env.NOW }}' \
          /repos/${{ github.repository }}/check-runs