name: 'Test reporting'

on:
  push:
  workflow_dispatch:
  pull_request:
  
permissions:
  contents: read
  actions: read
  checks: write  
  
jobs:
  build-and-test:
    name: 'Build, test and report'
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: 'Parse - Failing results'
        if: false
        uses: nih-milestone/trx-parser@v0.5.7
        with:
          TRX_PATH: ${{ github.workspace }}\FailingTestResults
          TRX_GROUPING: 50
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          
      - name: 'Parse - Passing results'
        if: false
        uses: nih-milestone/trx-parser@v0.5.7
        with:
          TRX_PATH: ${{ github.workspace }}\PassingTestResults
          TRX_GROUPING: 50
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set ENV variables
        run: |
          echo "BUILD_VERSION=1.2.3" >> $env:GITHUB_ENV
          echo "BUILD_SLN=Gate.slnf" >> $env:GITHUB_ENV

      - name: Create artifacts summary
        uses: ./.github/actions/create-artifacts-summary
        with:
          build-version: ${{ env.BUILD_VERSION }}
          solution: ${{ env.BUILD_SLN }}