name: 'Test reporting'

on:
  push:
  workflow_dispatch:
  
permissions:
  contents: read
  actions: read
  checks: write  
  
jobs:
  build-and-test:
    name: 'Build, test and report'
    runs-on: windows-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: 'Parse - Failing results'
        uses: nih-milestone/trx-parser@v0.5.7
        with:
          TRX_PATH: ${{ github.workspace }}\FailingTestResults
          TRX_GROUPING: 50
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          
      - name: 'Parse - Passing results'
        if: always()
        uses: nih-milestone/trx-parser@v0.5.7
        with:
          TRX_PATH: ${{ github.workspace }}\PassingTestResults
          TRX_GROUPING: 50
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}           